### ISSUE TITLE
plz add example with a for each loop 

### ISSUE THREAD

**Issue by frank-dspeed** [adamhalasz/diet-ect#1]
Hello i tryed this and i expirence problems i am not sure what exact is.

plz provide a example for looping over a object or array with for each via diet-ect

$.data.mynamesObj = [ 
{ name: blabla1, oha: value2 }
{ name: blabla1, oha: value2 }
{ name: blabla1, oha: value2 }
]

thx a lot

**Comment by adamhalasz** [comment]
Hi,

The official documentation explains how to loop over such an array at http://ectjs.com/ . ECT uses coffeescript inside the opening `{{` and closing `}}` tags, you can check out every kind of looping and instruction at http://coffeescript.org/

You can loop trough _your specific_ array like this:

``` coffeescript
{{ for row in this.mynamesObj : }}
    <h1>{{- row.name }}</h1>
    <p>{{- row.oha }}</p>
{{ end }}
```

Let me know if you have other questions!

Cheers,
Adam

**Comment by frank-dspeed** [comment]
thx so much that made clear for me that the documentation from ect realy works but the <% needs to be replaced with {{ 

:dancer:
